### ISSUE TITLE
Error when converting paf cs alignments

### ISSUE THREAD

**Issue by bistace** [slimsuite/buscomp#2]
Hello,
I tried to use BUSCOMP on the results of four BUSCOs but I am getting the following error:

```
#~~#    00:01:50        # ~~~~~~~~~~ PAF to Local Alignment Conversion ~~~~~~~~~~~ #
#DROP   00:01:50        31 local fields reduced to 16 fields
#SEQ    00:01:50        Making sequence name dictionaries...
#ALN    00:01:53        Converting PAF cs alignments: 3.1%
#ERR    00:01:53        BUSCOMP.pafToLocal error: <type 'IndexError'> (pafToLocal line 565) string index out of range
<type 'IndexError'>: string index out of range
File: /env/export/source/src/buscomp/buscomp_master/code/rje_paf.py
Method: pafToLocal (line 565)
Error: if cs[1] != sfull[0].lower(): swarnx += 1


#ERR    00:01:53        A running genome assembly of discovery consumes a pie of dreams: <type 'ValueError'> (run line 344)
<type 'ValueError'>:
File: /env/export/source/src/buscomp/buscomp_master/code/rje_paf.py
Method: run (line 344)
Error: if not self.pafToLocal(minlocid=self.getNum('MinLocID'),minloclen=self.getInt('MinLocLen')): raise ValueError
```
I have attached the log file, paf file and paf.cmd file, if that can help you.

[buscomp.zip](https://github.com/slimsuite/buscomp/files/3376108/buscomp.zip)

**Comment by slimsuite** [comment]
Thanks. I will look into it. (I should probably tone weed out instances of the random error message generator too! Entertaining for debugging, not so useful for users...)

**Comment by slimsuite** [comment]
Hi. I can't see anything wrong with the `*.paf` file that would give that error. Is it possible to share the `contigs_bionano.fasta` and `buscomp.buscomp.fasta` files with me, via FileSender or something? It looks like the parser is prematurely running out of hit sequence, so it would be useful to work out why.

**Comment by slimsuite** [comment]
I've updated the code to hopefully improve the error-handling of this part of the parsing. I'd still like to get to the bottom of what is causing the issue, but hopefully you can now run your data and it flag the problem line and continue, rather than crashing.

**Comment by bistace** [comment]
Thank you for  your fast response time. Unfortunately, I am not allowed to share fasta files but I was able to run your updated code and attached the buscomp.log file. I noticed these two lines:
```
900 of 901 sequences loaded from /env/cns/bigtmp2/ONT/test/bionano/hetre/buscomp/fasta/contigs_bionano.fasta (Format: fas).
624 of 625 sequences loaded from /env/cns/bigtmp2/ONT/test/bionano/hetre/buscomp/fasta/contigs_biscot.fasta (Format: fas).
```
This is on these two files that I am getting the paf cs conversion error so I looked at your upgraded debug log and noticed that it was always the same sequence generating errors. I looked at my fasta files and found that two different sequences had the same fasta header. Could this be the source of the error I am getting?

[buscomp.log](https://github.com/slimsuite/buscomp/files/3380659/buscomp.log)

**Comment by slimsuite** [comment]
Good spot. Yes, this is probably the problem. BUSCOMP assumes unique sequence naming and builds a dictionary of names pointing to sequences. If two have the same name, then one of them will point to the wrong sequence. I should really add a check for this. It's generally not a good idea to have two sequences with the same name - lots of programs, like BLAST+, will get messed up by it.

There is no requirement for the naming of the sequences to be consistent with the original BUSCO run, so I recommend renaming one of the sequences and re-running BUSCOMP.

**Comment by bistace** [comment]
Hello, just wanted to tell you that after renaming contigs so they have a unique name, BUSCOMP completed succesfully!

**Comment by slimsuite** [comment]
Thanks for the update.

**Comment by slimsuite** [comment]
From version 0.7.7 onwards, redundant sequence naming should be checked and raise an error.
