### ISSUE TITLE
Dropping genomes without sequence data

### ISSUE THREAD

**Issue by mneitzey** [slimsuite/buscomp#6]
Hello,

My run is unable to obtain sequence data for BUSCOMPseq, despite my 2 genome assemblies and results tables initially being read without issue. Also `single_copy_busco_sequences` directories exists within both run directories, and are not empty. See what I assume is the start of the issue being logged below:

`#DROP   00:01:04        Dropping 2 genomes without sequence data for BUSCOMPSeq compilation`  
`#DROP   00:01:04        1,914 buscoseq entries reduced to 0 entries on Genome.`

Which eventually leads to this error:

`#ERR    00:01:05        Cannot load sequences from shasta500b_2kb.buscomp.fasta. Might be empty?!`

I attached the log file for reference. Do you have any recommendations to make the sequence data processable? I would appreciate any assistance.

Michelle
[buscomp_log.txt](https://github.com/slimsuite/buscomp/files/4815442/buscomp_log.txt)

**Comment by cabbagesofdoom** [comment]
Hi @mneitzey. Sorry about this. You are right that it seems to be unable to recognise the `single_copy_busco_sequences` directory, but it sounds like it should. Is this BUSCO v3 or BUSCO v4 data? 

Can you also attach (or email me) the `shasta500b_2kb.genomes.tdt` file and the results of either:

`tree > shasta500b_2kb.tree.txt` if you have `tree` on your system, or `ls -lrhtR > shasta500b_2kb.ls.txt` if you don't? It would be helpful to see what is in those directories just in case there is something else breaking the content parser - I had to make some modifications to recognise both v3 and v4 output, and it's possible that I have missed a possible conflict.

You could also try renaming `run_metazoa_odb10_2/full_table_2kb.tsv` to `run_metazoa_odb10_2/full_table_metazoa_odb10_2.tsv` and `run_metazoa_odb10/full_table_500b.tsv` to `run_metazoa_odb10/full_table_metazoa_odb10.tsv` just in case that fixes it. (Though the current naming should work fine.)

I'll add a few more messages during the parsing and update the repo.

**Comment by cabbagesofdoom** [comment]
Hi @mneitzey, can you try the updated v0.9.3 just in case that fixes it? I realised that the repo version did not quite have all the final tweaks from the dev version.

**Comment by mneitzey** [comment]
Hello @cabbagesofdoom , thanks for your quick response. It will probably take a few days until I can get the updated version, but I will try it and let you know asap if that works. If not I'll send the info you requested. For the record it is BUSCO v4 data.

**Comment by slimsuite** [comment]
Hi @mneitzey, just wondering if this was now fixed and I can close the issue?

**Comment by mneitzey** [comment]
Hi @slimsuite , sorry for the lack of response. I work on an HPC and still haven't gotten the updated version, so I haven't resolved the issue, but I'm not sure when I'll be able to. Do with this issue what you see fit.

**Comment by slimsuite** [comment]
No worries. In case it helps, there's no installation necessary for BUSCOMP: just clone the repo into any directory and run the buscomp.py with python 2.x. I'll close the issue for now, but feel free to open another one if it keeps happening. BUSCO v5 is just out, so I'll be updating for that soon.
