### ISSUE TITLE
R added to path but getting BUSCOMP.rmdKnit error: check R installation

### ISSUE THREAD

**Issue by MarleyCodes** [slimsuite/buscomp#7]
Since I'm not admin, I added R 3.6.3 to my path but BUSCOMP seems to be unable to use R properly.

CMD:
python2.7 code/buscomp.py minimap2=minimap2-20180713/minimap2 runs=run_final*

**Comment by slimsuite** [comment]
Can you post the error that you are getting? It should be in the `buscomp.log` if you have not got a note of it. If you just run `R` on the command line, does it launch R? (`q()` to quit, I think.) If so, I think the R installation is fine. 

The main output will still be generated but you also need to have pandoc for the HTML output. The easist way to get it is to install RStudio and then export the path, along the lines of:

```
export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc
```

If this was the problem, you won't need to re-run the whole program to generate the output. You should be able to open up the Rmd files in RStudio and knit them there. Or run (replacing `<RMD_FILE>`):

```
Rscript -e 'library(rmarkdown); rmarkdown::render("<RMD_FILE>", "html_document")'
```

**Comment by MarleyCodes** [comment]
Thanks for the quick reply.

And yes I can run R from the command line, and RSTUDIO_PANDOC also works for pandoc.

I think this part of the log seems relevant here, if I missed something please let me know.

#SAVE   00:01:32        Table "rdata" saved to "buscomp.N3L20ID0U.rdata.tdt": 3 entries.
#==#    00:01:32        # ============================== SUMMARY RMARKDOWN OUTPUT ============================== #
#DROP   00:01:32        1,440 best entries reduced to 942 entries on Status.
#RMD    00:01:32        RMarkdown BUSCOMP summary output to buscomp.N3L20ID0U.Rmd
#RCMD   00:01:32        Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.Rmd", "html_document")'
#SYS    00:01:32        If pandoc error, try setting global variable: export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc
#SYS    00:01:32        If no pandoc error, check that required libraries in buscomp.N3L20ID0U.Rmd are installed
#ERR    00:01:32        BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.html not created  
#==#    00:01:32        # =============================== FULL RMARKDOWN OUTPUT ================================ #
#DROP   00:01:32        1,440 best entries reduced to 942 entries on Status.
#RMD    00:01:32        RMarkdown BUSCOMP summary output to buscomp.N3L20ID0U.full.Rmd
#RCMD   00:01:32        Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.full.Rmd", "html_document")'
#SYS    00:01:33        If pandoc error, try setting global variable: export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc
#SYS    00:01:33        If no pandoc error, check that required libraries in buscomp.N3L20ID0U.full.Rmd are installed
#ERR    00:01:33        BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.full.html not created  
#WARN   00:01:33        3 warning messages: check log for details.
#WARN   00:01:33        2 error messages! Check log for details.
#LOG    00:01:33        BUSCOMP V0.9.7 End: Fri Jan 29 11:13:23 2021
#~~#    #~+~~+~#        #~~#
#LOG    00:00:00        Activity Log for BUSCOMP V0.9.7: Fri Jan 29 11:20:35 2021
#DIR    00:00:00        Run from directory: /data/sag/2020/MYE_19070143_AnthuriumGenomeImprovement/ipa/dist/dist/19-final
#ARG    00:00:00        Commandline arguments: v
#CMD    00:00:00        Full Command List: log=buscomp.log v
#VIO    00:00:00        Verbosity: 1; Interactivity: 0.
#ERR    00:00:00        Problem with rje_db.Database.cmd:v<type 'ValueError'> (_cmdRead line 400) could not convert string to float:   
#ERR    00:00:00        Problem with <rje_rmd.Rmd object at 0x14bc12526610>.cmd:v<type 'ValueError'> (_cmdRead line 582) could not convert string to float:   
#ERR    00:00:00        Problem with <__main__.BUSCOMP object at 0x14bc125aba50>.cmd:v<type 'ValueError'> (_cmdRead line 582) could not convert string to float:   
#==#    00:00:00        # ================================= SETUP BUSCOMP RUN ================================== #
#ERR    00:00:00        Problem with rje_db.Table.cmd:v<type 'ValueError'> (_cmdRead line 400) could not convert string to float:   
#RUNDIR 00:00:00        run_final.p_ctg.IPA.busco run type: Single
#SEQDIR 00:00:00        Found SC BUSCO sequence directory: run_final.p_ctg.IPA.busco/single_copy_busco_sequences
#RUNDIR 00:00:00        Processed run_final.p_ctg.IPA.busco: 1 runs (1 total)
#RUNDIR 00:00:00        run_final.pa_ctg.IPA.busco run type: Single
#SEQDIR 00:00:00        Found SC BUSCO sequence directory: run_final.pa_ctg.IPA.busco/single_copy_busco_sequences
#RUNDIR 00:00:00        Processed run_final.pa_ctg.IPA.busco: 1 runs (2 total)
#==#    00:00:00        # =============================== MAPPING GENOME ALIASES =============================== #
#ERR    00:00:00        Problem with rje_db.Table.cmd:v<type 'ValueError'> (_cmdRead line 400) could not convert string to float:   
#LOAD   00:00:00        Loaded table "buscomp.genomes" renamed "alias".
#TABLE  00:00:00        Table "alias" added: 29 fields; 3 entries.
#ALIAS  00:00:00        final.p_ctg.IPA (final.p_ctg.fasta.busco): "final.p_ctg.fasta.busco" -> "final.p_ctg.IPA"
#ALIAS  00:00:00        Genome updated: final.p_ctg.IPA (final.p_ctg.fasta.busco)
#DESC   00:00:00        Description updated: final.p_ctg.IPA (final.p_ctg.fasta.busco) = "./final.p_ctg.fasta"
#ALIAS  00:00:00        final.pa_ctg.IPA (final.pa_ctg.fasta.busco): "final.pa_ctg.fasta.busco" -> "final.pa_ctg.IPA"
#ALIAS  00:00:00        Genome updated: final.pa_ctg.IPA (final.pa_ctg.fasta.busco)
#DESC   00:00:00        Description updated: final.pa_ctg.IPA (final.pa_ctg.fasta.busco) = "./final.pa_ctg.fasta"
#==#    00:00:00        # ================================ SETUP GENOME GROUPS ================================= #
#ERR    00:00:00        Problem with rje_db.Table.cmd:v<type 'ValueError'> (_cmdRead line 400) could not convert string to float:   
#LOAD   00:00:00        Loaded table "buscomp.groups" renamed "groups".
#TABLE  00:00:00        Table "groups" added: 3 fields; 2 entries.
#GRP    00:00:00        BUSCOMP: final.pa_ctg.IPA|final.p_ctg.IPA
#SORT   00:00:00        Genomes sorted by genome name and group
#ERR    00:00:30        Problem during BUSCOMP genomeMenu.: <type 'KeyboardInterrupt'> (choice line 2709)   



I tried running: Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.full.Rmd", "html_document")'

And got:
Error in library(rmarkdown) : there is no package called ‘rmarkdown’

**Comment by slimsuite** [comment]
Try running R and then:

```
install.packages("rmarkdown")
```

That should probably sort it for future runs too. If other packages are missing, you might want to install them through RStudio. (And please let me know what ones are needed, so I can update the docs!)

**Comment by slimsuite** [comment]
Actually, you will also need:

```
install.packages("ggplot2")
install.packages("ggrepel")
```

**Comment by MarleyCodes** [comment]
Thanks for the suggestions! I'm still getting errors, they are different this time though:

==#	00:00:34	# ============================== SUMMARY RMARKDOWN OUTPUT ============================== #
#DROP	00:00:34	1,440 best entries reduced to 942 entries on Status.
#RMD	00:00:34	RMarkdown BUSCOMP summary output to buscomp.N3L20ID0U.Rmd
#RCMD	00:00:34	Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.Rmd", "html_document")'
#SYS	00:00:34	If pandoc error, try setting global variable: export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc
#SYS	00:00:34	If no pandoc error, check that required libraries in buscomp.N3L20ID0U.Rmd are installed

#ERR	00:00:34	BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.html not created  
#==#	00:00:34	# =============================== FULL RMARKDOWN OUTPUT ================================ #
#DROP	00:00:34	1,440 best entries reduced to 942 entries on Status.
#RMD	00:00:34	RMarkdown BUSCOMP summary output to buscomp.N3L20ID0U.full.Rmd
#RCMD	00:00:34	Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.full.Rmd", "html_document")'
#SYS	00:00:35	If pandoc error, try setting global variable: export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc
#SYS	00:00:35	If no pandoc error, check that required libraries in buscomp.N3L20ID0U.full.Rmd are installed

#ERR	00:00:35	BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.full.html not created  
#WARN	00:00:35	3 warning messages: check log for details.     
#WARN	00:00:35	2 error messages! Check log for details.     
#LOG	00:00:35	BUSCOMP V0.9.7 End: Fri Jan 29 12:35:46 2021
Repeat 3 warnings? (y/n) [default=N]:  Repeat 2 error messages? (y/n) [default=Y]:  #ERR	00:00:34	BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.html not created  
#ERR	00:00:35	BUSCOMP.rmdKnit error: check R installation: <type 'IOError'> (rmdKnit line 266) buscomp.N3L20ID0U.full.html not created 


Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.Rmd", "html_document")'
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted

In my ~/.bashrc: export RSTUDIO_PANDOC=/data/tools/pandoc/bin/pandoc

and RSTUDIO_PANDOC -h shows the helppage of pandoc.

**Comment by slimsuite** [comment]
Try changing it to:

```
export RSTUDIO_PANDOC=/data/tools/pandoc/bin
```

**Comment by MarleyCodes** [comment]
Alright, that gave me a new error. And I'm afraid this could be caused by the server not supporting X11:

Rscript -e 'library(rmarkdown); rmarkdown::render("buscomp.N3L20ID0U.full.Rmd", "html_document")'


processing file: buscomp.N3L20ID0U.full.Rmd
  |.                                                                     |   1%
  ordinary text without R code

  |..                                                                    |   3%
label: setup (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 17-18 (buscomp.N3L20ID0U.full.Rmd) 
Error in dev.control(displaylist = if (record) "enable" else "inhibit") : 
  dev.control() called without an open graphics device
Calls: <Anonymous> ... call_block -> block_exec -> chunk_device -> dev.control
In addition: Warning messages:
1: In png(..., res = dpi, units = "in") :
  no png support in this version of R
2: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  unable to load shared object '/data/tools/R_3.6.3/R-3.6.3/lib/R/library/grDevices/libs//cairo.so':
  /data/tools/R_3.6.3/R-3.6.3/lib/R/library/grDevices/libs//cairo.so: cannot open shared object file: No such file or directory
3: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL

Execution halted

**Comment by cabbagesofdoom** [comment]
Sorry, this is looking a bit beyond my knowledge now. I think you might need to get some local support to get the Rscript command to work. Alternatively, copy the Rmd and results files (no need for the minimap directory) onto your desktop and simply knit the Rmd files in RStudio.

One reason I keep the Rmd files is in case people want to customise/expand the output, so this is something I tend to do anyway for analyses I care about.
